### PR TITLE
Clarify expectation vs prediction, deprecate estimate_response()

### PR DESCRIPTION
**Pull request by bwiernik**
Following https://github.com/easystats/insight/issues/432, `estimate_response()` was generating a warning, and it isn't clear whether it was an expectation or prediction (IMO). I think deprecating it, making it an alias for `estimate_expectation()` (to match `type="response"` in `predict.glm()`), and pushing users toward expectation/prediction would be good.

### CODE REVIEW

**Comment by strengejacke** [comment]
Ok, there seem to be the only these two doc-issue remaining here:

> Warning: prepare_Rd: estimate_response.Rd:65-67: Dropping empty section \details
> checkRd: (5) visualisation_recipe.estimate_predicted.Rd:262-268: Only one \description is allowed

**Comment by strengejacke** [comment]
Now only this one is left:

> Warning:   checkRd: (5) visualisation_recipe.estimate_predicted.Rd:262-268: Only one \description is allowed

**Comment by DominiqueMakowski** [comment]
on it

**Comment by strengejacke** [comment]
> on it

I really don't know which line belongs to which section when the `@` tags are missing ;-) I always explicitly write `@title`, `@description` for that reason...

**Comment by DominiqueMakowski** [comment]
Here the problem was that for some reason it is copying the @description from the original main definition in datawizard 🤔

**Comment by strengejacke** [comment]
Cool, looks ready to merge now!

**Comment by bwiernik** [comment]
Thanks folks!

**Pull request merged**
