### PR TITLE
v0.9 - API simplification

### PR DESCRIPTION
**Pull request by DominiqueMakowski**
I realized that there was no need for 2 arguments in `estimate_slopes`, previously it had `levels` and `modulate` meant respectively for factors and numerics, but actually with the improvements in the visualisation_matrix function + on emmeans's wrapping side, we can have a unique argument for both.

For now, I picked `at` (similarly to emmeans), but I hesitate with simply `modulate` or `focus`. It encompasses the variables that we want to "spread" and vary. Better name ideas are welcome. 

- [x] This API simplification probably applies to estimate_contrasts and estimate_means, I'll take a look at it

### CODE REVIEW

**Comment by bwiernik** [comment]
I like "at" or "levels". I find the focus and modulate labels confusing

**Comment by strengejacke** [comment]
I would go with `at` for now. `levels` is not quite appropriate for numerics, or?

**Comment by bwiernik** [comment]
I was thinking this was for values of the variable, not the variables themselves. 

`at` is a little confusing for me to refer to the variable names. Why not something more straightforward like `variable`?

**Comment by strengejacke** [comment]
> I was thinking this was for values of the variable, not the variables themselves.

Yes, this was my understanding as well. And thus, `levels` for values of numeric variables seems strange, that's why I vote for `at`.

**Comment by bwiernik** [comment]
`at` doesn't make sense to me. That suggests values, not names

Why not `variables`

**Comment by strengejacke** [comment]
> `at` doesn't make sense to me. That suggests values, not names

I thought we were talking about values?

e4713053e07addb52db822e7114bcd6a

**Comment by bwiernik** [comment]
> @param at The predictor variable(s) \emph{at} which to evaluate the desired effect / mean / contrasts. Other predictors of the model that are not included here will be collapsed and "averaged" over (the effect will be estimated across them).

**Comment by bwiernik** [comment]
How about, "variables", "along", "focus"?

**Comment by DominiqueMakowski** [comment]
image

**Comment by DominiqueMakowski** [comment]
It's almost good. Now I'm fightining with this weird phenomenon I do remember @strengejacke we've encountered in before, in which one particular "test" fails in the checks; but not locally, and if you comment it out the next "test" becomes the one that is failing. 

Right now it's :

```r
== Failed tests ================================================================
-- Error (test-estimate_means.R:110:5): estimate_means -------------------------
Error: 'length(x) = 3 > 1' in coercion to 'logical(1)'
Backtrace:
    x
 1. \-modelbased::estimate_means(model)
 2.   \-modelbased::model_emmeans(...)
 3.     \-modelbased:::.guess_emmeans_arguments(model, at, fixed, ...)

[ FAIL 1 | WARN 6 | SKIP 0 | PASS 165 ]
Error: Test failures
```

But it has nothing to do with this particular test. Daniel do you recall how we addressed this kind of weirdness in the past?

**Comment by DominiqueMakowski** [comment]
Well the github checks fail beacuse of `cannot open URL 'https://api.github.com/repos/easystats/datawizard/contents/DESCRIPTION?ref=HEAD'` @IndrajeetPatil is everything ok?

**Comment by DominiqueMakowski** [comment]
Indeed! @strengejacke how did u know it was there? nothing in the log pointed to here right?


--

Regarding the naming of `at`, the story I told myself was that you get means / contrasts "at" a given configuration of variables/specifications. E.g., I want the marginal effect of x "at [all levels of] the *f* factor". 

Note that the input of `at` can be pretty flexible:

``` r
model <- lm(Petal.Length ~ Sepal.Width * Species, data = iris)

modelbased::estimate_means(model, at = "Sepal.Width=c(2, 4)")
#> NOTE: Results may be misleading due to involvement in interactions
#> Estimated Marginal Means
#> 
#> Sepal.Width | Mean |   SE |       95% CI
#> ----------------------------------------
#> 2.00        | 3.28 | 0.10 | [3.07, 3.49]
#> 4.00        | 4.35 | 0.10 | [4.15, 4.55]
#> 
#> Marginal means estimated for Sepal.Width
modelbased::estimate_means(model, at = list("Sepal.Width" = c(2, 4)))
#> NOTE: Results may be misleading due to involvement in interactions
#> Estimated Marginal Means
#> 
#> Sepal.Width | Mean |   SE |       95% CI
#> ----------------------------------------
#> 2.00        | 3.28 | 0.10 | [3.07, 3.49]
#> 4.00        | 4.35 | 0.10 | [4.15, 4.55]
#> 
#> Marginal means estimated for Sepal.Width
modelbased::estimate_means(model, at = data.frame(Sepal.Width = c(2, 4)))
#> NOTE: Results may be misleading due to involvement in interactions
#> Estimated Marginal Means
#> 
#> Sepal.Width | Mean |   SE |       95% CI
#> ----------------------------------------
#> 2.00        | 3.28 | 0.10 | [3.07, 3.49]
#> 4.00        | 4.35 | 0.10 | [4.15, 4.55]
#> 
#> Marginal means estimated for Sepal.Width
```

<sup>Created on 2021-07-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by bwiernik** [comment]
Oh, okay. Didn't realize you could specify levels like that. "at" works then. Sorry for the hassle

**Comment by strengejacke** [comment]
> Indeed! @strengejacke how did u know it was there? nothing in the log pointed to here right?

_Everything_ in the log pointed to there:

```
Error: Error: 'length(x) = 3 > 1' in coercion to 'logical(1)'
Backtrace:
    █
 1. └─modelbased::estimate_means(model)
 2.   └─modelbased::model_emmeans(...)
 3.     └─modelbased:::.guess_emmeans_arguments(model, at, fixed, ...)
```

haha

**Pull request merged**
