### PR TITLE
Add model_marginaleffects to pkgdown reference list

### PR DESCRIPTION
**Pull request by moritzkoerber**
Currently, the pkgdown build workflow fails because `model_marginaleffects`  is not listed in the reference index: https://github.com/easystats/modelbased/runs/5433065598?check_suite_focus=true#step:10:66

See also the [pkgdown documentation](https://pkgdown.r-lib.org/reference/build_reference.html#missing-topics) on this.

This PR adds `model_marginaleffects` to the refences under "Miscellaenous".

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
Thanks!

Websites builds are still failing, but due to errors in vignettes.

@DominiqueMakowski The vignette build fails here:

```r
Quitting from lines 160-173 (describe_nonlinear.Rmd) 
Error in .get_datagrid_clean_target(x, ...) : 
```

**Comment by moritzkoerber** [comment]
> Thanks!
> 
> Websites builds are still failing, but due to errors in vignettes.
> 
> @DominiqueMakowski The vignette build fails here:
> 
> ```r
> Quitting from lines 160-173 (describe_nonlinear.Rmd) 
> Error in .get_datagrid_clean_target(x, ...) : 
> ```

Hm, could be that `target` is already given as an argument in an underlying function further down the line, e.g. in `insight::get_datagrid.data.frame`

**Comment by IndrajeetPatil** [comment]
Possible. Looks like this might be due to some internal restructuring of functions that has happened recently.

**Comment by DominiqueMakowski** [comment]
Thansk for the notif, will fix it

**Pull request merged**
