### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by DominiqueMakowski**

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
```
Thanks,

on its way to CRAN.
```
Finally 😅

**Comment by mattansb** [comment]
When trying to install from CRAN I get:
```R
#> Warning in install.packages :
#>   package ‘modelbased’ is not available (for R version 3.6.1)
```
Is this because the description file is missing `Depends: R (>= 3.0)`?

**Comment by DominiqueMakowski** [comment]
probably because `on_its_way() != is_already_on()` 😁

**Comment by DominiqueMakowski** [comment]
Takes a few hours/days for them to build, host, refresh the website etc ☺️

**Comment by mattansb** [comment]
AH, I thought that because the [link work](https://cran.r-project.org/package=modelbased) it would let me install ^_^

**Comment by DominiqueMakowski** [comment]
didn't see that! but if you look at the "binaries" they are all unavailable, so I guess it explains

**Pull request merged**
