### PR TITLE
fixes for CRAN

### PR DESCRIPTION
**Pull request by DominiqueMakowski**

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
@strengejacke I see you've already made fixes, is there anything left?

**Comment by strengejacke** [comment]
I think all our pkgs (effectsize, modelbased, bayestestR and performance) should be fixed. 

effectsize, performance and modelbased also have been fixed according to other suggested packages.

**Comment by strengejacke** [comment]
What is the current state? Already re-submitted?

**Comment by DominiqueMakowski** [comment]
Re-submitted (should have done it earlier but it's my turn to be sick 🤧)

**Comment by strengejacke** [comment]
:-/ get well soon! I thought Singapore is too warm to get ill. ;-)

**Comment by DominiqueMakowski** [comment]
> I thought Singapore is too warm to get ill. ;-)

Thought that too :)

Anyway, modelbased, effectsize and bayestestR are "on their way to CRAN" 🎉

**Pull request merged**
