### PR TITLE
Rename `at` arguments into `by`

### PR DESCRIPTION
**Pull request by strengejacke**
https://github.com/easystats/easystats/issues/404

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
Thanks Daniel :)

**Comment by strengejacke** [comment]
I hope all relevant code pieces are updated now. Still some failing checks, due to _report_, where we also need to make changes. Renaming the arguments throughout all packages will cause some uneasiness when submitting all updates to CRAN, I guess ;-)

**Comment by strengejacke** [comment]
@DominiqueMakowski The examples I removed in [this commit](https://github.com/easystats/modelbased/pull/255/commits/9233f1baa71188f52899c93f7151a4452fd37b34) are even not working with the current CRAN version of _modelbased_ - it's not related to this PR.

**Comment by strengejacke** [comment]
This error occurs when _ggplot2_ is loaded after _poorman_ (https://github.com/easystats/modelbased/actions/runs/9209112782/job/25332884239):

```
Caused by error:
! cannot xtfrm data frames
Backtrace:
     ▆
  1. └─... %>% summarise(RT = mean(RT))
  2.   └─base::eval(rhs_call, envir = list(. = lhs), enclos = parent.frame())
  3.     └─base::eval(rhs_call, envir = list(. = lhs), enclos = parent.frame())
  4.       ├─poorman::summarise(., RT = mean(RT))
  5.       └─poorman:::summarise.grouped_df(., RT = mean(RT))
  6.         └─poorman:::groups_set(res, groups[-n], group_by_drop_default(.data))
  7.           └─poorman:::calculate_groups(x, groups, drop)
  8.             ├─...[]
  9.             ├─tibble:::`[.tbl_df`(...)
 10.             ├─base::do.call(...)
 11.             └─base (local) `<fn>`(`<tibble[,1]>`, `<tibble[,1]>`)
 12.               └─base::lapply(z, function(x) if (is.object(x)) as.vector(xtfrm(x)) else x)
 13.                 └─base (local) FUN(X[[i]], ...)
 14.                   ├─base::as.vector(xtfrm(x))
 15.                   ├─base::xtfrm(x)
 16.                   └─base::xtfrm.data.frame(x)
```

**Pull request merged**
