### PR TITLE
`estimate_means(backend = "marginaleffects")` not calculating marginal means

### LINKED ISSUE #273: `estimate_means(backend = "marginaleffects")` not calculating marginal means
See:

``` r
data(Salamanders, package = "glmmTMB")
m <- glm(count ~ mined + spp, family = poisson(), data = Salamanders)
modelbased::estimate_means(m, "mined")
#> Estimated Marginal Means
#> 
#> mined | rate |   SE |       95% CI
#> ----------------------------------
#> yes   | 0.24 | 0.03 | [0.20, 0.30]
#> no    | 1.86 | 0.08 | [1.70, 2.03]
#> 
#> Marginal means estimated at mined
modelbased::estimate_means(m, "mined", backend = "marginaleffects")
#> Estimated Marginal Means
#> 
#> mined | spp | Mean |   SE |       95% CI
#> ----------------------------------------
#> yes   |  GP | 0.26 | 0.04 | [0.19, 0.33]
#> no    |  GP | 2.01 | 0.19 | [1.63, 2.39]
#> 
#> Marginal means estimated at mined
modelbased::estimate_expectation(m, insight::get_datagrid(m, "mined"))
#> Model-based Expectation
#> 
#> mined | Predicted |   SE |       95% CI
#> ---------------------------------------
#> yes   |      0.26 | 0.04 | [0.20, 0.34]
#> no    |      2.01 | 0.19 | [1.66, 2.43]
#> 
#> Variable predicted: count
#> Predictors modulated: mined
#> Predictors controlled: spp (GP)
```

<sup>Created on 2024-12-13 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

I think we need `avg_predictions()` here?

### PR DESCRIPTION
**Pull request by strengejacke**
Fixes #273

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
Should we add tests against emmeans, marginaleffects and ggeffects just so that we keep track of the similarities and discrepancies?

**Comment by strengejacke** [comment]
Yes this is still work in progress. I'll add tests and also contacts with marginaleffects engine.

**Comment by strengejacke** [comment]
One important thing is that we probably have to include a type dictionary:
https://github.com/vincentarelbundock/marginaleffects/blob/main/R/type_dictionary.R

Else, we have other default types, leading to different results compared to emmeans or marginaleffects. See examples here:
https://github.com/easystats/modelbased/issues/273#issuecomment-2542244287

**Comment by strengejacke** [comment]
Ok, I added a lot of tests (still more to come) and I think we now have the marginal means equivalent to emmeans with the marginaleffects-backend.

And we even have "marginal predictions" for random effects, which is what we should have, IMHO.

**Comment by strengejacke** [comment]
I think we could simplify `estimate_contrats()`, see new `get_marginalcontrasts()`. And I think we don't need the `contrast` argument, since `by` does this task. And we could then use `contrast` instead of `method`, because we can now also have flexible contrasts like `(b1-b3)=(b2-b4)` - in this case, `contrast` is a more appropriate name than `method`. WDYT?

**Comment by DominiqueMakowski** [comment]
The idea of having contrast and by is that there are cases where you want say the contrast between `levelA` and `levelB` at every level of some variable:

``` r
m <- lm(Sepal.Length ~ Species * Sepal.Width, data=iris)
modelbased::estimate_contrasts(m, contrast="Species", by="Sepal.Width")
#> Marginal Contrasts Analysis
#> 
#> Level1     |     Level2 | Sepal.Width | Difference |         95% CI |   SE
#> --------------------------------------------------------------------------
#> setosa     | versicolor |        2.00 |      -1.25 | [-1.97, -0.53] | 0.30
#> setosa     | versicolor |        2.27 |      -1.30 | [-1.86, -0.73] | 0.23
#> setosa     | versicolor |        2.53 |      -1.34 | [-1.78, -0.91] | 0.18
#> setosa     | versicolor |        2.80 |      -1.39 | [-1.72, -1.06] | 0.14
#> setosa     | versicolor |        3.07 |      -1.44 | [-1.73, -1.14] | 0.12
#> setosa     | versicolor |        3.33 |      -1.48 | [-1.83, -1.13] | 0.14
#> setosa     | versicolor |        3.60 |      -1.53 | [-1.99, -1.07] | 0.19
#> setosa     | versicolor |        3.87 |      -1.58 | [-2.18, -0.98] | 0.25
#> setosa     | versicolor |        4.13 |      -1.62 | [-2.37, -0.87] | 0.31
#> setosa     | versicolor |        4.40 |      -1.67 | [-2.58, -0.76] | 0.37
#> setosa     |  virginica |        2.00 |      -1.69 | [-2.45, -0.92] | 0.32
#> setosa     |  virginica |        2.27 |      -1.75 | [-2.36, -1.13] | 0.25
#> setosa     |  virginica |        2.53 |      -1.80 | [-2.27, -1.34] | 0.19
#> setosa     |  virginica |        2.80 |      -1.86 | [-2.20, -1.52] | 0.14
#> setosa     |  virginica |        3.07 |      -1.92 | [-2.18, -1.65] | 0.11
#> setosa     |  virginica |        3.33 |      -1.97 | [-2.25, -1.70] | 0.11
#> setosa     |  virginica |        3.60 |      -2.03 | [-2.40, -1.66] | 0.15
#> setosa     |  virginica |        3.87 |      -2.08 | [-2.59, -1.58] | 0.21
#> setosa     |  virginica |        4.13 |      -2.14 | [-2.79, -1.49] | 0.27
#> setosa     |  virginica |        4.40 |      -2.20 | [-3.00, -1.39] | 0.33
#> versicolor |  virginica |        2.00 |      -0.44 | [-1.07,  0.19] | 0.26
#> versicolor |  virginica |        2.27 |      -0.45 | [-0.91,  0.02] | 0.19
#> versicolor |  virginica |        2.53 |      -0.46 | [-0.78, -0.14] | 0.13
#> versicolor |  virginica |        2.80 |      -0.47 | [-0.70, -0.24] | 0.09
#> versicolor |  virginica |        3.07 |      -0.48 | [-0.74, -0.22] | 0.11
#> versicolor |  virginica |        3.33 |      -0.49 | [-0.87, -0.10] | 0.16
#> versicolor |  virginica |        3.60 |      -0.50 | [-1.04,  0.04] | 0.22
#> versicolor |  virginica |        3.87 |      -0.51 | [-1.22,  0.20] | 0.29
#> versicolor |  virginica |        4.13 |      -0.52 | [-1.40,  0.37] | 0.37
#> versicolor |  virginica |        4.40 |      -0.53 | [-1.59,  0.53] | 0.44
#> 
#> Level1     | t(144) |      p
#> ----------------------------
#> setosa     |  -4.23 | < .001
#> setosa     |  -5.53 | < .001
#> setosa     |  -7.51 | < .001
#> setosa     | -10.19 | < .001
#> setosa     | -11.79 | < .001
#> setosa     | -10.31 | < .001
#> setosa     |  -8.04 | < .001
#> setosa     |  -6.37 | < .001
#> setosa     |  -5.24 | < .001
#> setosa     |  -4.46 | < .001
#> setosa     |  -5.35 | < .001
#> setosa     |  -6.92 | < .001
#> setosa     |  -9.36 | < .001
#> setosa     | -13.24 | < .001
#> setosa     | -17.74 | < .001
#> setosa     | -17.37 | < .001
#> setosa     | -13.25 | < .001
#> setosa     | -10.02 | < .001
#> setosa     |  -7.95 | < .001
#> setosa     |  -6.60 | < .001
#> versicolor |  -1.69 | 0.092 
#> versicolor |  -2.34 | 0.021 
#> versicolor |  -3.49 | < .001
#> versicolor |  -4.97 | < .001
#> versicolor |  -4.45 | < .001
#> versicolor |  -3.07 | 0.003 
#> versicolor |  -2.22 | 0.028 
#> versicolor |  -1.73 | 0.086 
#> versicolor |  -1.42 | 0.158 
#> versicolor |  -1.21 | 0.230 
#> 
#> Marginal contrasts estimated at Species
#> p-value adjustment method: Holm (1979)
```

<sup>Created on 2024-12-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
You can get those with just `by`, however, this also includes pairwise combinations of different `Sepal.Width` values (you would need to filter...):

``` r
m <- lm(Sepal.Length ~ Species * Sepal.Width, data=iris)
marginaleffects::avg_predictions(
  m,
  newdata = insight::get_datagrid(m, by = c("Species", "Sepal.Width = [sd]")),
  by = c("Species", "Sepal.Width"),
  hypothesis = "pairwise"
)
#> 
#>                                         Term Estimate Std. Error       z
#>  setosa, 2.621467 - setosa, 3.057333          -0.3010     0.0722  -4.166
#>  setosa, 2.621467 - setosa, 3.493200          -0.6019     0.1445  -4.166
#>  setosa, 2.621467 - versicolor, 2.621467      -1.3584     0.1627  -8.347
#>  setosa, 2.621467 - versicolor, 3.057333      -1.7355     0.1700 -10.207
#>  setosa, 2.621467 - virginica, 2.621467       -1.8211     0.1741 -10.459
#>  setosa, 2.621467 - virginica, 3.057333       -2.2140     0.1608 -13.767
#>  setosa, 2.621467 - virginica, 3.493200       -2.6070     0.1893 -13.773
#>  setosa, 3.057333 - setosa, 3.493200          -0.3010     0.0722  -4.166
#>  setosa, 3.057333 - versicolor, 2.621467      -1.0574     0.1113  -9.499
#>  setosa, 3.057333 - versicolor, 3.057333      -1.4345     0.1217 -11.785
#>  setosa, 3.057333 - virginica, 2.621467       -1.5201     0.1274 -11.934
#>  setosa, 3.057333 - virginica, 3.057333       -1.9131     0.1085 -17.632
#>  setosa, 3.057333 - virginica, 3.493200       -2.3060     0.1474 -15.641
#>  setosa, 3.493200 - versicolor, 2.621467      -0.7565     0.0935  -8.094
#>  setosa, 3.493200 - versicolor, 3.057333      -1.1335     0.1056 -10.730
#>  setosa, 3.493200 - virginica, 2.621467       -1.2192     0.1121 -10.875
#>  setosa, 3.493200 - virginica, 3.057333       -1.6121     0.0901 -17.895
#>  setosa, 3.493200 - virginica, 3.493200       -2.0051     0.1345 -14.911
#>  versicolor, 2.621467 - versicolor, 3.057333  -0.3771     0.0873  -4.321
#>  versicolor, 2.621467 - virginica, 2.621467   -0.4627     0.1155  -4.007
#>  versicolor, 2.621467 - virginica, 3.057333   -0.8556     0.0942  -9.078
#>  versicolor, 2.621467 - virginica, 3.493200   -1.2486     0.1373  -9.094
#>  versicolor, 3.057333 - virginica, 2.621467   -0.0856     0.1255  -0.682
#>  versicolor, 3.057333 - virginica, 3.057333   -0.4786     0.1063  -4.500
#>  versicolor, 3.057333 - virginica, 3.493200   -0.8715     0.1459  -5.975
#>  virginica, 2.621467 - virginica, 3.057333    -0.3929     0.0849  -4.628
#>  virginica, 2.621467 - virginica, 3.493200    -0.7859     0.1698  -4.628
#>  virginica, 3.057333 - virginica, 3.493200    -0.3929     0.0849  -4.628
#>  Pr(>|z|)     S  2.5 % 97.5 %
#>    <0.001  15.0 -0.443 -0.159
#>    <0.001  15.0 -0.885 -0.319
#>    <0.001  53.7 -1.677 -1.039
#>    <0.001  78.8 -2.069 -1.402
#>    <0.001  82.6 -2.162 -1.480
#>    <0.001 140.8 -2.529 -1.899
#>    <0.001 140.9 -2.978 -2.236
#>    <0.001  15.0 -0.443 -0.159
#>    <0.001  68.7 -1.276 -0.839
#>    <0.001 104.1 -1.673 -1.196
#>    <0.001 106.6 -1.770 -1.270
#>    <0.001 228.7 -2.126 -1.700
#>    <0.001 180.8 -2.595 -2.017
#>    <0.001  50.6 -0.940 -0.573
#>    <0.001  86.8 -1.341 -0.926
#>    <0.001  89.1 -1.439 -0.999
#>    <0.001 235.5 -1.789 -1.436
#>    <0.001 164.6 -2.269 -1.742
#>    <0.001  16.0 -0.548 -0.206
#>    <0.001  14.0 -0.689 -0.236
#>    <0.001  63.0 -1.040 -0.671
#>    <0.001  63.2 -1.518 -0.979
#>     0.495   1.0 -0.332  0.160
#>    <0.001  17.2 -0.687 -0.270
#>    <0.001  28.7 -1.157 -0.586
#>    <0.001  18.0 -0.559 -0.227
#>    <0.001  18.0 -1.119 -0.453
#>    <0.001  18.0 -0.559 -0.227
#> 
#> Type:  response 
#> Columns: term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high
```

<sup>Created on 2024-12-15 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

Let's think a bit more about how we can implement this. Maybe we just keep the current interace/arguments.

**Comment by strengejacke** [comment]
btw, you get your result also without using `contrast`:

``` r
m <- lm(Sepal.Length ~ Species * Sepal.Width, data=iris)
modelbased::estimate_contrasts(m, by=c("Species", "Sepal.Width"))
#> No variable was specified for contrast estimation. Selecting `contrast =
#>   "Species"`.
#> Marginal Contrasts Analysis
#> 
#> Level1     |     Level2 | Sepal.Width | Difference |         95% CI |   SE
#> --------------------------------------------------------------------------
#> setosa     | versicolor |        2.00 |      -1.25 | [-1.97, -0.53] | 0.30
#> setosa     | versicolor |        2.27 |      -1.30 | [-1.86, -0.73] | 0.23
#> setosa     | versicolor |        2.53 |      -1.34 | [-1.78, -0.91] | 0.18
#> setosa     | versicolor |        2.80 |      -1.39 | [-1.72, -1.06] | 0.14
#> setosa     | versicolor |        3.07 |      -1.44 | [-1.73, -1.14] | 0.12
#> setosa     | versicolor |        3.33 |      -1.48 | [-1.83, -1.13] | 0.14
#> setosa     | versicolor |        3.60 |      -1.53 | [-1.99, -1.07] | 0.19
#> setosa     | versicolor |        3.87 |      -1.58 | [-2.18, -0.98] | 0.25
#> setosa     | versicolor |        4.13 |      -1.62 | [-2.37, -0.87] | 0.31
#> setosa     | versicolor |        4.40 |      -1.67 | [-2.58, -0.76] | 0.37
#> setosa     |  virginica |        2.00 |      -1.69 | [-2.45, -0.92] | 0.32
#> setosa     |  virginica |        2.27 |      -1.75 | [-2.36, -1.13] | 0.25
#> setosa     |  virginica |        2.53 |      -1.80 | [-2.27, -1.34] | 0.19
#> setosa     |  virginica |        2.80 |      -1.86 | [-2.20, -1.52] | 0.14
#> setosa     |  virginica |        3.07 |      -1.92 | [-2.18, -1.65] | 0.11
#> setosa     |  virginica |        3.33 |      -1.97 | [-2.25, -1.70] | 0.11
#> setosa     |  virginica |        3.60 |      -2.03 | [-2.40, -1.66] | 0.15
#> setosa     |  virginica |        3.87 |      -2.08 | [-2.59, -1.58] | 0.21
#> setosa     |  virginica |        4.13 |      -2.14 | [-2.79, -1.49] | 0.27
#> setosa     |  virginica |        4.40 |      -2.20 | [-3.00, -1.39] | 0.33
#> versicolor |  virginica |        2.00 |      -0.44 | [-1.07,  0.19] | 0.26
#> versicolor |  virginica |        2.27 |      -0.45 | [-0.91,  0.02] | 0.19
#> versicolor |  virginica |        2.53 |      -0.46 | [-0.78, -0.14] | 0.13
#> versicolor |  virginica |        2.80 |      -0.47 | [-0.70, -0.24] | 0.09
#> versicolor |  virginica |        3.07 |      -0.48 | [-0.74, -0.22] | 0.11
#> versicolor |  virginica |        3.33 |      -0.49 | [-0.87, -0.10] | 0.16
#> versicolor |  virginica |        3.60 |      -0.50 | [-1.04,  0.04] | 0.22
#> versicolor |  virginica |        3.87 |      -0.51 | [-1.22,  0.20] | 0.29
#> versicolor |  virginica |        4.13 |      -0.52 | [-1.40,  0.37] | 0.37
#> versicolor |  virginica |        4.40 |      -0.53 | [-1.59,  0.53] | 0.44
#> 
#> Level1     | t(144) |      p
#> ----------------------------
#> setosa     |  -4.23 | < .001
#> setosa     |  -5.53 | < .001
#> setosa     |  -7.51 | < .001
#> setosa     | -10.19 | < .001
#> setosa     | -11.79 | < .001
#> setosa     | -10.31 | < .001
#> setosa     |  -8.04 | < .001
#> setosa     |  -6.37 | < .001
#> setosa     |  -5.24 | < .001
#> setosa     |  -4.46 | < .001
#> setosa     |  -5.35 | < .001
#> setosa     |  -6.92 | < .001
#> setosa     |  -9.36 | < .001
#> setosa     | -13.24 | < .001
#> setosa     | -17.74 | < .001
#> setosa     | -17.37 | < .001
#> setosa     | -13.25 | < .001
#> setosa     | -10.02 | < .001
#> setosa     |  -7.95 | < .001
#> setosa     |  -6.60 | < .001
#> versicolor |  -1.69 | 0.092 
#> versicolor |  -2.34 | 0.021 
#> versicolor |  -3.49 | < .001
#> versicolor |  -4.97 | < .001
#> versicolor |  -4.45 | < .001
#> versicolor |  -3.07 | 0.003 
#> versicolor |  -2.22 | 0.028 
#> versicolor |  -1.73 | 0.086 
#> versicolor |  -1.42 | 0.158 
#> versicolor |  -1.21 | 0.230 
#> 
#> Marginal contrasts estimated at Species
#> p-value adjustment method: Holm (1979)
```

<sup>Created on 2024-12-15 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
What is the purpose of `fixed`? Can't we just use `by` directly?

``` r
dat <- mtcars
dat[c("gear", "vs", "am")] <- lapply(dat[c("gear", "vs", "am")], as.factor)
dat$am
#>  [1] 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 1 1 1 1 1 1 1
#> Levels: 0 1
model <- lm(mpg ~ gear * vs * am, data = dat)
modelbased::estimate_means(model, fixed = "am")
#> We selected `by = c("gear", "vs", "am")`.
#> Estimated Marginal Means
#> 
#> am | gear | vs |  Mean |   SE |         95% CI
#> ----------------------------------------------
#> 0  |    3 |  0 | 15.05 | 1.04 | [12.90, 17.20]
#> 0  |    4 |  0 |       |      |               
#> 0  |    5 |  0 |       |      |               
#> 0  |    3 |  1 | 20.33 | 2.09 | [16.03, 24.63]
#> 0  |    4 |  1 | 21.05 | 1.81 | [17.33, 24.77]
#> 0  |    5 |  1 |       |      |               
#> 
#> Marginal means estimated at gear
modelbased::estimate_means(model, by = c("gear", "vs", "am = '0'"))
#> Estimated Marginal Means
#> 
#> gear | vs | am |  Mean |   SE |         95% CI
#> ----------------------------------------------
#> 3    |  0 |  0 | 15.05 | 1.04 | [12.90, 17.20]
#> 4    |  0 |  0 |       |      |               
#> 5    |  0 |  0 |       |      |               
#> 3    |  1 |  0 | 20.33 | 2.09 | [16.03, 24.63]
#> 4    |  1 |  0 | 21.05 | 1.81 | [17.33, 24.77]
#> 5    |  1 |  0 |       |      |               
#> 
#> Marginal means estimated at gear
```

<sup>Created on 2024-12-15 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by DominiqueMakowski** [comment]
fixed was just to "fix" variables at specific values, i.e. explicitly fix them without marginalizing over them

**Comment by strengejacke** [comment]
Yes, but see my example, where you get the same result with `by`

**Comment by DominiqueMakowski** [comment]
ah yes fair then, yes I agree it makes sense to streamline the API here. For `contrast` I'm less sure, I think it makes sense for users to specify explicitly the variables we want to contrast and dissociate that from the rest

**Comment by strengejacke** [comment]
> ah yes fair then, yes I agree it makes sense to streamline the API here. For `contrast` I'm less sure, I think it makes sense for users to specify explicitly the variables we want to contrast and dissociate that from the rest

ok. what about changing `method` to `test`? That's a more generic name for it, allowing to use the flexible options from _marginaleffects_ for `hypothesis`.

**Comment by strengejacke** [comment]
ok, when these tests pass, I'd like to merge this PR and open a new one for contrasts, and then a new one for slopes.

Tests are validated against our emmeans-engine, so we can - for `estimate_means()` - safely change the default backend to `"marginaleffects"`, if you like.

**Pull request merged**
