### PR TITLE
Prepare CRAN release

### PR DESCRIPTION
**Pull request by strengejacke**

### CODE REVIEW

**Comment by strengejacke** [comment]
```
Examples with CPU (user + system) or elapsed time > 10s
                    user system elapsed
estimate_contrasts 11.19   0.81   12.03
```

It seems like it's always these examples, we should probably deactivate most of them on CRAN and rely on GH tests

**Comment by strengejacke** [comment]
@DominiqueMakowski for discussion...

**Comment by DominiqueMakowski** [comment]
https://win-builder.r-project.org/IWWbF3M34R66/00check.log latest

**Comment by strengejacke** [comment]
Ok, I think you can submit from this branch. There's no hurry, CRAN page says: "[issues need fixing before 2024-11-07]". Let me know if I can help with the submission.

**Pull request merged**
