### PR TITLE
estimate_relation: plotting improvements

### PR DESCRIPTION
**Pull request by strengejacke**
This PR aims at revising `visualization_recipe` to plot at-targets in their given order. See #199, #201, #189 and #145

### CODE REVIEW

**Comment by strengejacke** [comment]
Far from perfect, but... ;-)

``` r
library(modelbased)
m <- lm(Sepal.Width ~ Petal.Length + Petal.Width + Species, data = iris)
modelbased::estimate_expectation(m, insight::get_datagrid(iris, "Species")) |> plot()
```



``` r
modelbased::estimate_expectation(m, insight::get_datagrid(iris, "Petal.Width")) |> plot()
```



``` r
m <- lm(Sepal.Width ~ Petal.Length + Petal.Width * Species, data = iris)
modelbased::estimate_expectation(m, insight::get_datagrid(iris, c("Petal.Width", "Species"))) |> plot()
```



``` r
modelbased::estimate_expectation(m, insight::get_datagrid(iris, c("Species", "Petal.Width"), range = "grid")) |> plot()
```



``` r
m <- lm(Sepal.Width ~ Petal.Length + Petal.Width * Species, data = iris)
mb <- modelbased::estimate_expectation(m, insight::get_datagrid(iris, c("Species", "Petal.Width"), range = "grid"))
plot(visualisation_recipe(mb, show_data = "none"))
```



``` r
ggeffects::ggpredict(m, c("Species", "Petal.Width")) |> plot()
```



``` r
ggeffects::ggpredict(m, c("Species", "Petal.Width")) |> plot(add.data = TRUE)
```



<sup>Created on 2022-08-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DominiqueMakowski** [comment]
could we use pointrange instead of error bars, same as in ggpredict? Should we merge this before I submit?

**Comment by strengejacke** [comment]
Yeah, pointrange is probably better. I'm not sure if we should merge before submission, you can take a look at this draft and decide. I'm not super familiar with `visualization_recipe()`, also because I'm not super familiar with the latest changes of the past months in ggplot. So I'm not sure whether and where this draft needs improvements.

**Comment by strengejacke** [comment]
Feel free to add, revise, remove, ... here

**Comment by DominiqueMakowski** [comment]
> because I'm not super familiar with the latest changes of the past months in ggplot.

what changes? 🤔

**Comment by strengejacke** [comment]
I have given a lecture on ggplot somewhen in 2019 or so... all the changes since then. :-)
Since I'm working on easystats, I'm no longer following the development of tidyverse, so all I know about dplyr are the five verbs select, filter, mutate, summarize and group_by or so.

**Comment by strengejacke** [comment]
(although this has different motivations: I don't see the need for following all details of dply and tidyr, but ggplot is _the_ top vis-package, I just wasn't following due to lack of time.

**Comment by DominiqueMakowski** [comment]
I refactored the code according to what we said and tested it for most variations, of course for some of them it's a bit messy and require further customization but I think it's a fairly good basis

``` r
library(modelbased)
library(ggplot2)
library(rstanarm)
#> Warning: package 'rstanarm' was built under R version 4.2.1
#> Loading required package: Rcpp
#> This is rstanarm version 2.21.3
#> - See https://mc-stan.org/rstanarm/articles/priors for changes to default priors!
#> - Default priors may change, so it's safest to specify priors, even if equivalent to the defaults.
#> - For execution on a local, multicore CPU with excess RAM we recommend calling
#>   options(mc.cores = parallel::detectCores())

# Customize aesthetics
layers <- visualisation_recipe(x,
                               point = list(color = "red", alpha = 0.6, size = 3),
                               line = list(color = "blue", size = 3),
                               ribbon = list(fill = "green", alpha = 0.7),
                               labs = list(subtitle = "Oh yeah!")
)
#> Error in visualisation_recipe(x, point = list(color = "red", alpha = 0.6, : object 'x' not found
layers
#> Error in eval(expr, envir, enclos): object 'layers' not found
plot(layers)
#> Error in plot(layers): object 'layers' not found

# Customize raw data
plot(visualisation_recipe(x, show_data = "none"))
#> Error in visualisation_recipe(x, show_data = "none"): object 'x' not found
plot(visualisation_recipe(x, show_data = c("density_2d", "points")))
#> Error in visualisation_recipe(x, show_data = c("density_2d", "points")): object 'x' not found
plot(visualisation_recipe(x, show_data = "density_2d_filled"))
#> Error in visualisation_recipe(x, show_data = "density_2d_filled"): object 'x' not found
plot(visualisation_recipe(x, show_data = "density_2d_polygon"))
#> Error in visualisation_recipe(x, show_data = "density_2d_polygon"): object 'x' not found
plot(visualisation_recipe(x, show_data = "density_2d_raster")) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(expand = c(0, 0))
#> Error in visualisation_recipe(x, show_data = "density_2d_raster"): object 'x' not found

# Single predictors examples -----------

plot(estimate_relation(lm(Sepal.Length ~ Sepal.Width, data = iris)))
```



``` r
plot(estimate_relation(lm(Sepal.Length ~ Species, data = iris)))
```



``` r

# 2-ways interaction ------------

# Numeric * numeric
x <- estimate_relation(lm(mpg ~ wt * qsec, data = mtcars))
layers <- visualisation_recipe(x)
plot(layers)
```



``` r

# Numeric * factor
x <- estimate_relation(lm(Sepal.Width ~ Sepal.Length * Species, data = iris))
layers <- visualisation_recipe(x)
plot(layers)
```



``` r

# Factor * numeric
x <- estimate_relation(lm(Sepal.Width ~ Species * Sepal.Length, data = iris))
layers <- visualisation_recipe(x)
plot(layers)
```



``` r

# 3-ways interaction ------------

data <- mtcars
data$vs <- as.factor(data$vs)
data$cyl <- as.factor(data$cyl)
data$new_factor <- as.factor(rep(c("A", "B"), length.out = nrow(mtcars)))

# Numeric * numeric * numeric
x <- estimate_relation(lm(mpg ~ wt * qsec * hp, data = data), length=c(5, 3, 20))
layers <- visualisation_recipe(x)
plot(layers)
```



``` r

# Numeric * numeric * factor
x <- estimate_relation(lm(mpg ~ wt * am * vs, data = data))
layers <- visualisation_recipe(x)
plot(layers)
```



``` r

# Numeric * factor * factor
x <- estimate_relation(lm(mpg ~ wt * cyl * new_factor, data = data))
layers <- visualisation_recipe(x)
plot(layers)
```



``` r

# Factor * numeric * numeric
x <- estimate_relation(lm(mpg ~ cyl * qsec * hp, data = data))
layers <- visualisation_recipe(x)
plot(layers) +
  scale_size_continuous(range=c(0.2, 1))
```



``` r

# GLMs ---------------------
x <- estimate_relation(glm(vs ~ mpg, data = mtcars, family = "binomial"))
plot(visualisation_recipe(x))
```



``` r
plot(visualisation_recipe(x, show_data = "jitter", point = list(height = 0.03)))
```



``` r

# Multiple CIs ---------------------
plot(estimate_relation(lm(mpg ~ disp, data = mtcars),
                       ci = c(.50, .80, .95)))
```



``` r
plot(estimate_relation(lm(Sepal.Length ~ Species, data = iris),
                       ci = c(0.5, 0.7, 0.95)))
```



``` r


# Bayesian models ---------------------

model <- rstanarm::stan_glm(mpg ~ wt, data = mtcars, refresh = 0)

# Plot individual draws instead of regular ribbon
x <- estimate_relation(model, keep_iterations = 100)
layers <- visualisation_recipe(x, ribbon = list(color = "red"))
plot(layers)
```



``` r

model <- rstanarm::stan_glm(Sepal.Width ~ Species * Sepal.Length, data = iris, refresh = 0)
plot(estimate_relation(model, keep_iterations = 100))
```



<sup>Created on 2022-08-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by bwiernik** [comment]
I'll take a look this week or weekend

**Comment by DominiqueMakowski** [comment]
Since the deadline for CRAN update is tomorrow, I'd say I merge and submit, and then we can refine for the next version?

**Comment by DominiqueMakowski** [comment]
@IndrajeetPatil tests tail on R < 4.1 because of emmeans hard requirement. Should we drop testing on these versions?

**Comment by IndrajeetPatil** [comment]
Hmm, a more fine-grained and better approach would be to set `testthat::skip_if_not_installed("emmeans")` only for tests that need `{emmeans}`, and run all other tests on supported R versions.

**Comment by strengejacke** [comment]
Let's see if checks are ok when suggested packages are not available.

**Comment by strengejacke** [comment]
I think the new vis-recipe is definitely an improvement! Great work, Dom! I'm ok with merging it into this release. And I think, CRAN doesn't check on R < 4.1 anyway, so there shouldn't be any problems.

**Pull request merged**
